/*
联通Cookie获取

[rewrite_local]
https:\/\/m\.client\.10010\.com\/(.*)\/smartwisdomCommon  url script-request-header https://raw.githubusercontent.com/dompling/Script/master/10010/index.js

[mitm]
hostname = m.client.10010.com
*/
